// NOTE Quiz Settings will be used to set the quiz parameters

const MILLISECONDS_PER_QUESTION = 10000
const SECONDS_PER_QUESTION = MILLISECONDS_PER_QUESTION / 1000

export { MILLISECONDS_PER_QUESTION, SECONDS_PER_QUESTION }
